services:
  - type: web
    name: weather-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: WEATHER_API_KEY
        value: 
      - key: MONGO_URI
        value: 
